using GameEditor.GameData;
using GameEditor.MapEditor;
using GameEditor.TilesetEditor;
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Dynamic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace GameEditor.ProjectIO
{
    public class GameDataWriter : IDisposable
    {
        private bool disposed;
        protected IdentifierNamespace identifiers = new IdentifierNamespace();
        protected StreamWriter f;
        protected uint syncBits;
        protected int dataSize;

        public GameDataWriter(string filename, byte vgaSyncBits) {
            f = new StreamWriter(filename, false, Encoding.UTF8);
            f.NewLine = "\n";
            syncBits = ((uint) vgaSyncBits) & 0xc0;
            Util.Log($"-> got sync bits {syncBits} from {vgaSyncBits}");
        }

        public void Dispose() {
            if (disposed) return;
            f.Dispose();
            GC.SuppressFinalize(this);
            disposed = true;
        }

        protected void BeginWrite() {
            dataSize = 0;
            f.WriteLine($"// Auto-generated by GameEditor at {DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")}");
            f.WriteLine();
            f.WriteLine("#include \"game_data.h\"");
            f.WriteLine();
            f.WriteLine($"#define GAME_DATA_VGA_SYNC_BITS 0x{syncBits:x02}");
            f.WriteLine();
        }

        protected void EndWrite() {
            f.WriteLine($"// total data size: {dataSize} bytes");
            f.Close();
        }

        protected byte EncodeColor(byte red, byte green, byte blue) {
            uint r = ((uint) red   >> 6) & 0x3;
            uint g = ((uint) green >> 6) & 0x3;
            uint b = ((uint) blue  >> 6) & 0x3;
            return (byte) (syncBits | (b<<4) | (g<<2) | r);
        }

        protected void WriteTilesetData(Tileset tileset) {
            string ident = identifiers.Add(tileset, "game_tileset_data", tileset.Name);
            f.Write($"static const uint32_t {ident}[] = ");
            f.WriteLine("{");

            const int tileSize = Tileset.TILE_SIZE;
            const int numBlocksPerTile = tileSize * tileSize / 4;

            byte[] bmp = new byte[4 * tileSize * tileSize];
            for (int tile = 0; tile < tileset.NumTiles; tile++) {
                tileset.ReadTilePixels(tile, bmp);
                f.Write($"  // tile {tile}");
                for (int bl = 0; bl < numBlocksPerTile; bl++) {
                    if (bl % 8 == 0) {
                        f.WriteLine();
                        f.Write("  ");
                    }
                    uint block = 0;
                    for (int p = 0; p < 4; p++) {
                        byte b = bmp[bl*16 + p*4 + 0];
                        byte g = bmp[bl*16 + p*4 + 1];
                        byte r = bmp[bl*16 + p*4 + 2];
                        block |= ((uint) EncodeColor(r, g, b)) << (p*8);
                    }
                    f.Write("0x{0:x08},", block);
                }
                f.WriteLine();
                dataSize += bmp.Length;
            }

            f.WriteLine("};");
            f.WriteLine();
        }

        protected void WriteTilesets() {
            foreach (TilesetItem ti in EditorState.TilesetList) {
                WriteTilesetData(ti.Tileset);
            }
            f.WriteLine("const struct GAME_IMAGE game_tilesets[] = {");
            const int size = Tileset.TILE_SIZE;
            foreach (TilesetItem ti in EditorState.TilesetList) {
                string ident = identifiers.Get(ti.Tileset);
                f.WriteLine($"  {{ {size}, {size}, {size/4}, {ti.Tileset.NumTiles}, {ident} }},");
                dataSize += 5 * 4;  // 4 * int32_t + 1*intptr_t
            }
            f.WriteLine("};");
            f.WriteLine();
        }

        protected void WriteMapTiles(MapData map) {
            string ident = identifiers.Add(map, "game_map_tiles", map.Name);
            MapTiles tiles = map.Tiles;
            f.Write($"static const uint8_t {ident}[] = ");
            f.WriteLine("{");
            f.Write("  // background");
            for (int y = 0; y < tiles.Height; y++) {
                for (int x = 0; x < tiles.Width; x++) {
                    if ((y*tiles.Width + x) % 16 == 0) { f.WriteLine(); f.Write("  "); }
                    f.Write($"0x{tiles.bg[x,y]&0xff:x02},");
                }
            }
            f.WriteLine();
            f.Write("  // foreground");
            for (int y = 0; y < tiles.Height; y++) {
                for (int x = 0; x < tiles.Width; x++) {
                    if ((y*tiles.Width + x) % 16 == 0) { f.WriteLine(); f.Write("  "); }
                    f.Write($"0x{tiles.fg[x,y]&0xff:x02},");
                }
            }
            f.WriteLine();
            f.Write("  // collision");
            for (int y = 0; y < tiles.Height; y++) {
                for (int x = 0; x < tiles.Width; x++) {
                    if ((y*tiles.Width + x) % 16 == 0) { f.WriteLine(); f.Write("  "); }
                    f.Write($"0x{tiles.clip[x,y]&0xff:x02},");
                }
            }
            f.WriteLine();
            f.WriteLine("};");
            f.WriteLine();
            dataSize += 3 * tiles.Width * tiles.Height;
        }
        protected void WriteMaps() {
            foreach (MapDataItem mi in EditorState.MapList) {
                WriteMapTiles(mi.Map);
            }

            Dictionary<Tileset, int>? tsIndices = new Dictionary<Tileset, int>();
            foreach (var (ti, index) in EditorState.TilesetList.Zip(Enumerable.Range(0, EditorState.TilesetList.Count))) {
                tsIndices[ti.Tileset] = index;
            }

            f.WriteLine("const struct GAME_MAP game_maps[] = {");
            foreach (MapDataItem mi in EditorState.MapList) {
                string tiles = identifiers.Get(mi.Map);
                string tileset = $"game_tilesets[{EditorState.GetTilesetIndex(mi.Map.Tileset)}]";
                f.WriteLine($"  {{ {mi.Map.Tiles.Width}, {mi.Map.Tiles.Height}, {tileset}, {tiles} }},");
            }
            f.WriteLine("};");
            f.WriteLine();
            dataSize += 2*2 + 2*4;  // 2*int16_t + 2*intptr_t
        }

        public void WriteProject() {
            BeginWrite();
            WriteTilesets();
            WriteMaps();
            EndWrite();
        }
    }
}
