using GameEditor.GameData;
using GameEditor.MapEditor;
using GameEditor.Misc;
using GameEditor.ModEditor;
using GameEditor.SfxEditor;
using GameEditor.SpriteEditor;
using GameEditor.TilesetEditor;
using System;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.Data.Common;
using System.Dynamic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace GameEditor.ProjectIO
{
    public class GameDataWriter : IDisposable
    {
        const string PREFIX_GAME_TILESET_DATA = "game_tileset_data";
        const string PREFIX_GAME_SPRITE_DATA = "game_sprite_data";
        const string PREFIX_GAME_MAP_TILES = "game_map_tiles";
        const string PREFIX_GAME_SFX_SAMPLES = "game_sfx_samples";
        const string PREFIX_GAME_MOD_SAMPLES = "game_mod_samples";
        const string PREFIX_GAME_MOD_PATTERN = "game_mod_pattern";
        const string PREFIX_GAME_SPRITE_ANIMATION = "GAME_SPRITE_ANIMATION";

        private bool disposed;
        protected IdentifierNamespace identifiers = new IdentifierNamespace();
        protected StreamWriter f;
        protected uint syncBits;

        public GameDataWriter(string filename, byte vgaSyncBits) {
            f = new StreamWriter(filename, false, Encoding.UTF8);
            f.NewLine = "\n";
            syncBits = ((uint) vgaSyncBits) & 0xc0;
            Util.Log($"-> got sync bits {syncBits} from {vgaSyncBits}");
        }

        public void Dispose() {
            if (disposed) return;
            f.Dispose();
            GC.SuppressFinalize(this);
            disposed = true;
        }

        protected void BeginWrite() {
            f.WriteLine($"// Auto-generated by GameEditor at {DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")}");
            f.WriteLine();
            f.WriteLine("#include \"game_data.h\"");
            f.WriteLine();
            f.WriteLine($"#define GAME_DATA_VGA_SYNC_BITS 0x{syncBits:x02}");
            f.WriteLine();
        }

        protected void EndWrite(int dataSize) {
            f.WriteLine($"// total data size: {dataSize} bytes");
            f.Close();
        }

        protected byte EncodeColor(byte red, byte green, byte blue) {
            uint r = ((uint) red   >> 6) & 0x3;
            uint g = ((uint) green >> 6) & 0x3;
            uint b = ((uint) blue  >> 6) & 0x3;
            return (byte) (syncBits | (b<<4) | (g<<2) | r);
        }

        // =============================================================
        // === MOD
        // =============================================================

        protected void WriteModData(ModData mod) {
            ModFile file = mod.ModFile;

            // sample data
            for (int spl = 0; spl < file.NumSamples; spl++) {
                if (file.Sample[spl].Len == 0) continue;
                string sampleIdent = identifiers.Add(file.Sample[spl], PREFIX_GAME_MOD_SAMPLES, mod.Name, $"sample{spl+1:D02}");
                f.Write($"static const int8_t {sampleIdent}[] = {{");
                for (int i = 0; i < file.Sample[spl].Len; i++) {
                    if (i % 16 == 0) { f.WriteLine(); f.Write("  "); }
                    f.Write($"{file.Sample[spl].Data[i]},");
                }
                f.WriteLine();
                f.WriteLine("};");
                f.WriteLine();
            }

            // patterns
            string ident = identifiers.Add(file.Pattern, PREFIX_GAME_MOD_PATTERN, mod.Name);
            f.Write($"static const GAME_MOD_CELL {ident}[] = {{");
            int cell = 0;
            for (int pat = 0; pat < file.NumPatterns; pat++) {
                for (int row = 0; row < 64; row++) {
                    for (int chan = 0; chan < file.NumChannels; chan++) {
                        if (cell % 4 == 0) {
                            f.WriteLine();
                            f.Write("  ");
                            if (cell % (64*file.NumChannels) == 0) {
                                f.WriteLine($"// pattern {pat}");
                                f.Write("  ");
                            }
                        }
                        f.Write($"{{ {file.Pattern[cell].Sample,2}, {file.Pattern[cell].Period,5}, 0x{file.Pattern[cell].Effect:x03}, }}, ");
                        cell++;
                    }
                }
            }
            f.WriteLine();
            f.WriteLine("};");
            f.WriteLine();
        }

        protected void WriteMod(ModData mod) {
            ModFile file = mod.ModFile;

            f.WriteLine("  {");

            // samples
            f.WriteLine("    // samples:");
            for (int spl = 0; spl < file.NumSamples; spl++) {
                string splIdent = (file.Sample[spl].Len == 0) ? "NULL" : identifiers.Get(file.Sample[spl]);
                f.Write("    {");
                f.Write($" {file.Sample[spl].Len,5}, {file.Sample[spl].LoopStart,5}, {file.Sample[spl].LoopLen,5},");
                f.Write($" {file.Sample[spl].Finetune}, {file.Sample[spl].Volume,2}, {splIdent}, ");
                f.WriteLine("},");
            }

            // song positions
            f.WriteLine("    // song positions:");
            f.Write($"    {file.NumSongPositions}, {{");
            for (int sp = 0; sp < file.NumSongPositions; sp++) {
                if (sp % 16 == 0) { f.WriteLine(); f.Write("      "); }
                f.Write($"{file.SongPositions[sp],3},");
            }
            f.WriteLine();
            f.WriteLine("    },");

            // channel, pattern
            f.WriteLine("    // num channels, pattern:");
            string patternIdent = identifiers.Get(file.Pattern);
            f.WriteLine($"    {file.NumChannels}, {file.NumPatterns}, {patternIdent},");

            f.WriteLine("  },");
        }

        protected int WriteMods() {
            f.WriteLine("// ================================================================");
            f.WriteLine("// === MOD");
            f.WriteLine("// ================================================================");
            f.WriteLine();
            foreach (ModDataItem mi in EditorState.ModList) {
                WriteModData(mi.Mod);
            }

            int dataSize = 0;
            f.WriteLine("const struct GAME_MOD game_mod[] = {");
            foreach (ModDataItem mi in EditorState.ModList) {
                WriteMod(mi.Mod);
                dataSize += mi.Mod.GameDataSize;
            }
            f.WriteLine("};");
            f.WriteLine();
            return dataSize;
        }

        // =============================================================
        // === SFX
        // =============================================================

        protected void WriteSfxData(SfxData sfx) {
            string ident = identifiers.Add(sfx, PREFIX_GAME_SFX_SAMPLES, sfx.Name);
            f.Write($"static const uint8_t {ident}[] = {{");
            for (int i = 0; i < sfx.NumSamples; i++) {
                if (i % 16 == 0) { f.WriteLine(); f.Write("  "); }
                f.Write($"0x{sfx.Data[i+SoundUtil.WAV_SAMPLES_OFFSET]:x02},");
            }
            f.WriteLine();
            f.WriteLine("};");
            f.WriteLine();
        }

        protected int WriteSfxs() {
            f.WriteLine("// ================================================================");
            f.WriteLine("// === SFX");
            f.WriteLine("// ================================================================");
            f.WriteLine();
            foreach (SfxDataItem si in EditorState.SfxList) {
                WriteSfxData(si.Sfx);
            }

            int dataSize = 0;
            f.WriteLine("const struct GAME_SFX game_sfx[] = {");
            foreach (SfxDataItem si in EditorState.SfxList) {
                string name = identifiers.Get(si.Sfx);
                f.WriteLine($"  {{ {si.Sfx.NumSamples}, {name} }},");
                dataSize += si.Sfx.GameDataSize;
            }
            f.WriteLine("};");
            f.WriteLine();
            return dataSize;
        }

        // =============================================================
        // === TILESETS
        // =============================================================

        protected void WriteTilesetData(Tileset tileset) {
            string ident = identifiers.Add(tileset, PREFIX_GAME_TILESET_DATA, tileset.Name);
            f.WriteLine($"static const uint32_t {ident}[] = {{");

            const int tileSize = Tileset.TILE_SIZE;
            const int numBlocksPerTile = tileSize * tileSize / 4;

            byte[] bmp = new byte[4 * tileSize * tileSize];
            for (int tile = 0; tile < tileset.NumTiles; tile++) {
                tileset.ReadTilePixels(tile, bmp);
                f.Write($"  // tile {tile}");
                for (int bl = 0; bl < numBlocksPerTile; bl++) {
                    if (bl % 8 == 0) {
                        f.WriteLine();
                        f.Write("  ");
                    }
                    uint block = 0;
                    for (int p = 0; p < 4; p++) {
                        byte b = bmp[bl*16 + p*4 + 0];
                        byte g = bmp[bl*16 + p*4 + 1];
                        byte r = bmp[bl*16 + p*4 + 2];
                        block |= ((uint) EncodeColor(r, g, b)) << (p*8);
                    }
                    f.Write("0x{0:x08},", block);
                }
                f.WriteLine();
            }

            f.WriteLine("};");
            f.WriteLine();
        }

        protected int WriteTilesets() {
            f.WriteLine("// ================================================================");
            f.WriteLine("// === TILESETS");
            f.WriteLine("// ================================================================");
            f.WriteLine();
            foreach (TilesetItem ti in EditorState.TilesetList) {
                WriteTilesetData(ti.Tileset);
            }

            int dataSize = 0;
            const int size = Tileset.TILE_SIZE;
            f.WriteLine("const struct GAME_IMAGE game_tilesets[] = {");
            foreach (TilesetItem ti in EditorState.TilesetList) {
                string ident = identifiers.Get(ti.Tileset);
                f.WriteLine($"  {{ {size}, {size}, {size/4}, {ti.Tileset.NumTiles}, {ident} }},");
                dataSize += ti.Tileset.GameDataSize;
            }
            f.WriteLine("};");
            f.WriteLine();
            return dataSize;
        }

        // =============================================================
        // === SPRITES
        // =============================================================

        protected void WriteSpriteData(Sprite sprite) {
            string ident = identifiers.Add(sprite, PREFIX_GAME_SPRITE_DATA, sprite.Name);
            f.WriteLine($"static const uint32_t {ident}[] = {{");

            int numBlocksPerLine = (sprite.Width+3) / 4;

            byte[] bmp = new byte[4 * sprite.Width * sprite.Height];
            for (int frame = 0; frame < sprite.NumFrames; frame++) {
                sprite.ReadFramePixels(frame, bmp);
                f.Write($"  // frame {frame}");
                for (int y = 0; y < sprite.Height; y++) {
                    for (int bl = 0; bl < numBlocksPerLine; bl++) {
                        if (bl % 8 == 0) {
                            f.WriteLine();
                            f.Write("  ");
                        }
                        int numPixelsInBlock = 4 - int.Clamp(4*(bl+1)-sprite.Width, 0, 3);
                        uint block = 0;
                        for (int p = 0; p < numPixelsInBlock; p++) {
                            byte b = bmp[y*sprite.Width*4 + bl*16 + p*4 + 0];
                            byte g = bmp[y*sprite.Width*4 + bl*16 + p*4 + 1];
                            byte r = bmp[y*sprite.Width*4 + bl*16 + p*4 + 2];
                            block |= ((uint) EncodeColor(r, g, b)) << (p*8);
                        }
                        // to be safe, ensure the padding also has the VGA bits set:
                        for (int p = numPixelsInBlock; p < 4; p++) {
                            block |= ((uint) EncodeColor(0, 0, 0)) << (p*8);
                        }
                        f.Write("0x{0:x08},", block);
                    }
                }
                f.WriteLine();
            }

            f.WriteLine("};");
            f.WriteLine();
        }

        protected int WriteSprites() {
            f.WriteLine("// ================================================================");
            f.WriteLine("// === SPRITES");
            f.WriteLine("// ================================================================");
            f.WriteLine();
            foreach (SpriteItem si in EditorState.SpriteList) {
                WriteSpriteData(si.Sprite);
            }

            int dataSize = 0;
            f.WriteLine("const struct GAME_IMAGE game_sprites[] = {");
            foreach (SpriteItem si in EditorState.SpriteList) {
                int w = si.Sprite.Width;
                int h = si.Sprite.Height;
                int nFrames = si.Sprite.NumFrames;
                string ident = identifiers.Get(si.Sprite);
                f.WriteLine($"  {{ {w}, {h}, {(w+3)/4}, {nFrames}, {ident} }},");
                dataSize += si.Sprite.GameDataSize;
            }
            f.WriteLine("};");
            f.WriteLine();
            return dataSize;
        }

        // =============================================================
        // === MAPS
        // =============================================================

        protected void WriteMapTiles(MapData map) {
            string ident = identifiers.Add(map, PREFIX_GAME_MAP_TILES, map.Name);
            MapTiles tiles = map.Tiles;
            f.WriteLine($"static const uint8_t {ident}[] = {{");
            f.Write("  // background");
            for (int y = 0; y < tiles.Height; y++) {
                for (int x = 0; x < tiles.Width; x++) {
                    if ((y*tiles.Width + x) % 16 == 0) { f.WriteLine(); f.Write("  "); }
                    f.Write($"0x{tiles.bg[x,y]&0xff:x02},");
                }
            }
            f.WriteLine();
            f.Write("  // foreground");
            for (int y = 0; y < tiles.Height; y++) {
                for (int x = 0; x < tiles.Width; x++) {
                    if ((y*tiles.Width + x) % 16 == 0) { f.WriteLine(); f.Write("  "); }
                    f.Write($"0x{tiles.fg[x,y]&0xff:x02},");
                }
            }
            f.WriteLine();
            f.Write("  // collision");
            for (int y = 0; y < tiles.Height; y++) {
                for (int x = 0; x < tiles.Width; x++) {
                    if ((y*tiles.Width + x) % 16 == 0) { f.WriteLine(); f.Write("  "); }
                    f.Write($"0x{tiles.clip[x,y]&0xff:x02},");
                }
            }
            f.WriteLine();
            f.WriteLine("};");
            f.WriteLine();
        }
        protected int WriteMaps() {
            f.WriteLine("// ================================================================");
            f.WriteLine("// === MAPS");
            f.WriteLine("// ================================================================");
            f.WriteLine();
            foreach (MapDataItem mi in EditorState.MapList) {
                WriteMapTiles(mi.Map);
            }

            Dictionary<Tileset, int>? tsIndices = new Dictionary<Tileset, int>();
            foreach (var (ti, index) in EditorState.TilesetList.Zip(Enumerable.Range(0, EditorState.TilesetList.Count))) {
                tsIndices[ti.Tileset] = index;
            }

            int dataSize = 0;
            f.WriteLine("const struct GAME_MAP game_maps[] = {");
            foreach (MapDataItem mi in EditorState.MapList) {
                string tiles = identifiers.Get(mi.Map);
                string tileset = $"game_tilesets[{EditorState.GetTilesetIndex(mi.Map.Tileset)}]";
                f.WriteLine($"  {{ {mi.Map.Tiles.Width}, {mi.Map.Tiles.Height}, {tileset}, {tiles} }},");
                dataSize += mi.Map.GameDataSize;
            }
            f.WriteLine("};");
            f.WriteLine();
            return dataSize;
        }

        // =============================================================
        // === SPRITE ANIMATIONS
        // =============================================================

        protected int WriteSpriteAnimations() {
            f.WriteLine("// ================================================================");
            f.WriteLine("// === SPRITE ANIMATIONS");
            f.WriteLine("// ================================================================");
            f.WriteLine();

            f.WriteLine($"enum GAME_SPRITE_ANIMATION_IDS {{");
            foreach (SpriteAnimationItem ai in EditorState.SpriteAnimationList) {
                string ident = identifiers.Add(ai.Animation, PREFIX_GAME_SPRITE_ANIMATION,
                                               ai.Animation.Name, "", IdentifierNamespace.UPPER_CASE);
                f.WriteLine($"  {ident},");
            }
            f.WriteLine("};");

            Dictionary<Sprite, int>? sprIndices = new Dictionary<Sprite, int>();
            foreach (var (si, index) in EditorState.SpriteList.Zip(Enumerable.Range(0, EditorState.SpriteList.Count))) {
                sprIndices[si.Sprite] = index;
            }

            int dataSize = 0;
            f.WriteLine("const struct GAME_SPRITE_ANIMATION game_sprite_animations[] = {");
            foreach (SpriteAnimationItem ai in EditorState.SpriteAnimationList) {
                string animName = identifiers.Get(ai.Animation);
                string sprite = $"game_sprites[{EditorState.GetSpriteIndex(ai.Animation.Sprite)}]";
                f.WriteLine($"  {{  // {animName}");
                f.WriteLine($"    {sprite},");
                f.WriteLine($"    {ai.Animation.NumLoops-1},");
                f.WriteLine("    {");
                foreach (SpriteAnimationLoop loop in ai.Animation.GetAllLoops()) {
                    if (loop.IsImmutable) continue;  // skip "all frames" loop
                    f.Write($"      {{ {loop.NumFrames}, {{ ");
                    for (int i = 0; i < loop.NumFrames; i++) {
                        f.Write($"{loop.Frame(i)},");
                    }
                    f.WriteLine(" } },");
                }
                f.WriteLine("    },");
                f.WriteLine("  },");
                dataSize += ai.Animation.GameDataSize;
            }
            f.WriteLine("};");
            f.WriteLine();

            return dataSize;
        }


        // =============================================================
        // === PROJECT
        // =============================================================

        public void WriteProject() {
            BeginWrite();
            int dataSize = 0;
            dataSize += WriteMods();
            dataSize += WriteSfxs();
            dataSize += WriteTilesets();
            dataSize += WriteSprites();
            dataSize += WriteMaps();
            dataSize += WriteSpriteAnimations();
            EndWrite(dataSize);
        }
    }
}
